export type Lang = 'en' | 'te'

export const business = {
  name: 'Ruhi Trends',
  shortName: 'Ruhi Trends',
  boutiqueName: "Ruhi's Boutique",
  siteUrl: 'https://ruhitrends.com',
  domain: 'ruhitrends.com',
  owner: 'Ruhi',
  phone: '+919908185597',
  phoneDisplay: '9908185597',
  whatsapp: '919908185597',
  justdialUrl:
    'https://www.justdial.com/Hyderabad/Ruhis-Botique-Opposite-Basket-Ball-Ground-Kukatpally/040PXX40-XX40-240824180839-T6T3_BZDET',
  mapsShareUrl:
    "https://www.google.com/maps/search/?api=1&query=Ruhi's+Boutique+Opposite+Basketball+Ground+Kukatpally+Hyderabad",
  mapsSearchUrl:
    "https://www.google.com/maps/search/?api=1&query=LIG-140+Opposite+Basketball+Ground+KPHB+7th+Phase+Kukatpally",
  mapsEmbedUrl:
    'https://www.google.com/maps?q=17.4728,78.3923&z=16&output=embed',
  lat: 17.4728,
  lng: 78.3923,
}

export const address = {
  plot: 'LIG-140',
  landmark: 'Opposite Basketball Ground',
  locality: 'KPHB 7th Phase, Kukatpally',
  city: 'Hyderabad',
  state: 'Telangana',
  pin: '500072',
  country: 'India',
  line: 'Plot No. LIG-140, Opposite Basketball Ground, KPHB 7th Phase, Kukatpally, Hyderabad, Telangana 500072, India',
}

export const collections = [
  {
    id: 'saree',
    image: '/col-saree.jpg',
    en: { title: 'Sarees & blouses', body: 'Silks, georgettes, and everyday drapes — finished with custom blouse work that fits.' },
    te: { title: 'చీరలు & బ్లౌజులు', body: 'సిల్క్, జార్జెట్, రోజువారీ చీరలు — కస్టమ్ బ్లౌజ్ స్టిచింగ్‌తో.' },
  },
  {
    id: 'lehenga',
    image: '/col-lehenga.jpg',
    en: { title: 'Lehengas', body: 'Festive and party lehengas styled for movement, with careful fitting and finishing.' },
    te: { title: 'లెహెంగాలు', body: 'పార్టీ, పండుగ లెహెంగాలు — ఫిట్టింగ్, ఫినిషింగ్ బూటిక్‌లోనే.' },
  },
  {
    id: 'bridal',
    image: '/col-bridal.jpg',
    en: { title: 'Bridal & occasion', body: 'Bridal consultations, measurements, and timelines planned for wedding week calm.' },
    te: { title: 'బ్రైడల్ & సందర్భాలు', body: 'బ్రైడల్ వేర్ కన్సల్టేషన్, కొలతలు, టైమ్‌లైన్ ప్లానింగ్.' },
  },
  {
    id: 'kurti',
    image: '/col-kurti.jpg',
    en: { title: 'Kurtis & daily wear', body: 'Easy ethnic looks for workdays, evenings, and everything between.' },
    te: { title: 'కుర్తీలు & డైలీ వేర్', body: 'పని, ఇంటికి సౌకర్యవంతమైన కుర్తీలు మరియు ఎత్నిక్ లుక్‌లు.' },
  },
  {
    id: 'kids',
    image: '/col-kids.jpg',
    en: { title: 'Kids wear', body: 'Festive little looks for family functions — soft fabrics, neat finishes.' },
    te: { title: 'పిల్లల దుస్తులు', body: 'పండుగలు, కుటుంబ వేడుకలకు అందమైన పిల్లల ఎత్నిక్ దుస్తులు.' },
  },
  {
    id: 'alter',
    image: '/col-alter.jpg',
    en: { title: 'Alterations', body: 'Precise alterations and restyling so the piece you love sits perfectly.' },
    te: { title: 'ఆల్టరేషన్స్', body: 'బ్లౌజ్, చీర, గౌన్‌లకు త్వరిత ఆల్టరేషన్ మరియు రీస్టైలింగ్.' },
  },
] as const

export const gallery = [
  { src: '/gallery-saree.jpg', en: 'Saree floor', te: 'చీరల ఫ్లోర్' },
  { src: '/gallery-bridal.jpg', en: 'Bridal looks', te: 'బ్రైడల్ లుక్‌లు' },
  { src: '/gallery-stitch.jpg', en: 'Custom stitch desk', te: 'కస్టమ్ స్టిచ్ డెస్క్' },
  { src: '/gallery-fitting.jpg', en: 'Fitting room', te: 'ఫిట్టింగ్ రూమ్' },
] as const

export const atelierServices = [
  {
    id: 'blouse',
    en: { title: 'Blouse stitching', body: 'Measured in-house, finished with clean edges and neat lining.', eta: 'Usually 3–5 days' },
    te: { title: 'బ్లౌజ్ స్టిచింగ్', body: 'ఇంట్లో కొలతలు — చక్కని ఎడ్జ్, లైనింగ్ ఫినిష్.', eta: 'సాధారణంగా 3–5 రోజులు' },
  },
  {
    id: 'alter',
    en: { title: 'Alterations', body: 'Length, fit, and restyle for saree blouses, lehengas, and kurtis.', eta: 'Often same / next day' },
    te: { title: 'ఆల్టరేషన్స్', body: 'పొడవు, ఫిట్, రీస్టైల్ — బ్లౌజ్, లెహెంగా, కుర్తీ.', eta: 'తరచు అదే / తర్వాత రోజు' },
  },
  {
    id: 'lehenga',
    en: { title: 'Lehenga & party', body: 'Festive sets tailored for movement, comfort, and occasion polish.', eta: 'Plan 7–12 days' },
    te: { title: 'లెహెంగా & పార్టీ', body: 'కదలిక, సౌకర్యం, సందర్భ ఫినిష్‌కు తగిన ఫిట్టింగ్.', eta: '7–12 రోజులు ప్లాన్ చేయండి' },
  },
  {
    id: 'bridal',
    en: { title: 'Bridal atelier', body: 'Consultations, trials, and wedding-week timelines handled calmly.', eta: 'Start 4–8 weeks early' },
    te: { title: 'బ్రైడల్ అటెలియర్', body: 'కన్సల్టేషన్, ట్రయల్స్, పెళ్లి వారం టైమ్‌లైన్ ప్రశాంతంగా.', eta: '4–8 వారాల ముందు ప్రారంభం' },
  },
] as const

export const bridalTimeline = [
  {
    id: 'consult',
    en: { when: '4–8 weeks before', title: 'Private consult', body: 'Mood, silhouette, fabric, and occasion plan.' },
    te: { when: '4–8 వారాల ముందు', title: 'ప్రైవేట్ కన్సల్ట్', body: 'లుక్, సిల్హౌట్, ఫ్యాబ్రిక్, సందర్భ ప్లాన్.' },
  },
  {
    id: 'measure',
    en: { when: '3–5 weeks before', title: 'Measure & trial', body: 'Precise measurements, first trial, and detailing notes.' },
    te: { when: '3–5 వారాల ముందు', title: 'కొలతలు & ట్రయల్', body: 'ఖచ్చితమైన కొలతలు, మొదటి ట్రయల్, డీటెయిలింగ్.' },
  },
  {
    id: 'finish',
    en: { when: '1–2 weeks before', title: 'Final finish', body: 'Last adjustments so the look sits perfectly on the day.' },
    te: { when: '1–2 వారాల ముందు', title: 'ఫైనల్ ఫినిష్', body: 'రోజున సరిగ్గా కూర్చునేలా చివరి అడ్జస్ట్‌మెంట్స్.' },
  },
] as const

export const faqs = [
  {
    id: 'walkin',
    en: {
      q: 'Can I walk in without a reservation?',
      a: 'Yes — walk-ins are welcome during boutique hours. Reserving helps us keep quiet time for fittings and bridal consults.',
    },
    te: {
      q: 'రిజర్వేషన్ లేకుండా వచ్చే వచ్చా?',
      a: 'అవును — బూటిక్ సమయాల్లో వెల్కమ్. రిజర్వ్ చేస్తే ఫిట్టింగ్‌లు, బ్రైడల్ కన్సల్ట్‌లకు ప్రశాంత సమయం ఉంటుంది.',
    },
  },
  {
    id: 'fabric',
    en: {
      q: 'Do you work with my own fabric?',
      a: 'Yes. Bring your saree, blouse piece, or fabric — we measure, stitch, and finish it in the atelier.',
    },
    te: {
      q: 'నా ఫ్యాబ్రిక్‌తో స్టిచ్ చేస్తారా?',
      a: 'అవును. చీర, బ్లౌజ్ పీస్ లేదా ఫ్యాబ్రిక్ తీసుకురండి — కొలతలు, స్టిచ్, ఫినిష్ అటెలియర్‌లోనే.',
    },
  },
  {
    id: 'urgent',
    en: {
      q: 'Can you take urgent alterations?',
      a: 'Often yes for simple alterations, depending on the day’s queue. Call or WhatsApp and we will confirm the same day.',
    },
    te: {
      q: 'అత్యవసర ఆల్టరేషన్ చేస్తారా?',
      a: 'సాధారణ ఆల్టరేషన్‌లకు తరచు అవును — రోజు క్యూ మీద ఆధారపడి. కాల్ లేదా వాట్సాప్ చేస్తే అదే రోజు నిర్ధారిస్తాం.',
    },
  },
  {
    id: 'kids',
    en: {
      q: 'Do you stitch kids ethnic wear?',
      a: 'Yes — festive kids looks for family functions, with soft fabrics and neat finishing.',
    },
    te: {
      q: 'పిల్లల ఎత్నిక్ వేర్ స్టిచ్ చేస్తారా?',
      a: 'అవును — కుటుంబ వేడుకలకు సాఫ్ట్ ఫ్యాబ్రిక్, చక్కని ఫినిష్‌తో పిల్లల లుక్‌లు.',
    },
  },
] as const


const dict = {
  en: {
    topStatsFallback: 'Designer boutique · Kukatpally',
    hours: 'Open daily · 10:00 AM – 8:30 PM',
    navHome: 'Home',
    navCollections: 'Collections',
    navAbout: 'Visit us',
    navBook: 'Reserve a visit',
    navStitch: 'Custom stitch',
    navAdmin: 'Admin',
    bookNow: 'Reserve a visit',
    callNow: 'Call now',
    whatsapp: 'WhatsApp',
    heroKicker: 'KPHB 7th Phase · Kukatpally',
    heroBrand: 'Ruhi Trends',
    heroSub: 'Custom stitching & designer ethnic wear',
    heroTagline: 'Silk, stitch and occasion couture. Finished with quiet care in Kukatpally, Hyderabad.',
    ctaQuote: 'Reserve a fitting',
    galleryTitle: 'The atelier',
    galleryIntro: 'Where fabric meets finish — saree drapes, bridal fittings, and custom stitch.',
    lookbookTitle: 'Collections',
    lookbookIntro: 'A richer edit of what we create, style, and finish for you.',
    atmosphereLabel: 'Atelier',
    atmosphereBody: 'Opposite the basketball ground · KPHB Phase 7 · Daily 10 AM – 8:30 PM',
    trustStripTitle: 'Trusted neighbourhood boutique',
    trustLiveLabel: 'At the boutique now',
    trustHours: 'Daily 10 AM – 8:30 PM',
    trustHub: 'KPHB 7th Phase',
    trustLandmark: 'Opp. basketball ground',
    trustLandmarkDetail: 'KPHB Phase 7',
    trustStitch: 'Custom stitch',
    trustStitchDetail: 'Blouse to bridal',
    finalCtaTitle: 'Your look, finished with care',
    finalCtaBody: 'Arrange a visit, request stitching, or call — we confirm fittings with the same-day clarity fashion deserves.',
    whyTitle: 'The Ruhi Trends difference',
    whyIntro: 'An intimate Kukatpally atelier for custom ethnic wear — measured, finished, and followed through.',
    why1Title: 'Bespoke stitching',
    why1Body: 'Blouses to bridal sets — measured in-house and finished with precise detailing.',
    why2Title: 'Occasion ready',
    why2Body: 'Weddings, receptions, and festive looks planned around your timeline.',
    why3Title: 'Easy to find',
    why3Body: 'LIG-140, opposite the basketball ground in KPHB 7th Phase.',
    why4Title: 'Effortless scheduling',
    why4Body: 'Reserve a visit or stitch request online — confirmed by phone or WhatsApp.',
    backLabel: '← Back',
    backHome: 'Back to home',
    roleTitle: 'Begin your look',
    roleVisitTitle: 'Private boutique visit',
    roleVisitBody: 'Sarees, bridal wear, and fittings — reserved time with our desk.',
    roleStitchTitle: 'Custom stitch request',
    roleStitchBody: 'Tell us the garment, fabric notes, and when you need it.',
    roleOfficeTitle: 'Speak with us',
    roleOfficeBody: 'Call Ruhi Trends for quick guidance on fittings and timelines.',
    roleVisitCta: 'Reserve visit',
    roleStitchCta: 'Start request',
    roleCallCta: 'Call now',
    collectionsTitle: 'The atelier edit',
    collectionsIntro: 'From everyday ethnic elegance to bridal statement pieces — each look curated and finished in our Kukatpally atelier.',
    exploreCollection: 'Explore',
    liveBoardTitle: 'Boutique desk',
    liveBoardIntro: 'Open visit requests and active stitching work at the boutique.',
    liveAppointmentsTitle: 'Visit requests',
    liveOrdersTitle: 'Stitching orders',
    liveEmptyAppointments: 'No open visits yet. Reserve a visit above.',
    liveEmptyOrders: 'No open stitch orders yet. Request custom stitching above.',
    liveColService: 'Service',
    liveColGarment: 'Garment',
    liveColWhen: 'When',
    liveColStatus: 'Status',
    marketPulse: 'At the boutique now',
    snapAppointments: 'Open visits',
    snapOrders: 'Active orders',
    snapReady: 'Ready to collect',
    aboutTitle: 'Visit Ruhi Trends',
    aboutIntro: 'Find us opposite the basketball ground in KPHB 7th Phase, Kukatpally.',
    aboutOwnerLabel: 'Boutique',
    aboutPhoneLabel: 'Phone',
    aboutAddressLabel: 'Address',
    aboutHoursLabel: 'Hours',
    aboutHoursValue: 'Daily · 10:00 AM – 8:30 PM',
    aboutBody:
      'Ruhi Trends (Ruhi\'s Boutique) offers custom stitching, bridal consultations, sarees, lehengas, kurtis, kids ethnic wear, and alterations. Walk in or reserve ahead so we can set aside time for measurements.',
    aboutMapTitle: 'Location map',
    ctaDirections: 'Directions',
    justdial: 'Justdial listing',
    googleReviews: 'reviews',
    bookTitle: 'Reserve a boutique visit',
    bookIntro: 'Share what you need — we will confirm your fitting by phone or WhatsApp.',
    stitchTitle: 'Request custom stitching',
    stitchIntro: 'Share garment details. The boutique will follow up for measurements and fabric.',
    name: 'Your name',
    phone: 'Phone / WhatsApp',
    serviceType: 'Service',
    garmentType: 'Garment type',
    fabricNotes: 'Fabric / colour notes',
    occasion: 'Occasion',
    preferredDate: 'Preferred date',
    preferredTime: 'Preferred time',
    notes: 'Notes',
    submitting: 'Sending…',
    submitBook: 'Reserve visit',
    submitStitch: 'Request stitching',
    formOfficeNote: 'We usually reply the same day during boutique hours.',
    serviceConsultation: 'Consultation',
    serviceStitching: 'Stitching',
    serviceBridal: 'Bridal',
    serviceAlteration: 'Alteration',
    serviceParty: 'Party wear',
    garmentBlouse: 'Blouse',
    garmentSaree: 'Saree set',
    garmentLehenga: 'Lehenga',
    garmentKurti: 'Kurti',
    garmentKids: 'Kids wear',
    garmentAlteration: 'Alteration',
    garmentOther: 'Other',
    timeMorning: 'Morning',
    timeAfternoon: 'Afternoon',
    timeEvening: 'Evening',
    confirmBookTitle: 'Visit request received',
    confirmStitchTitle: 'Stitching request received',
    confirmBackHome: 'Back to home',
    confirmAnotherBook: 'Reserve another visit',
    confirmAnotherStitch: 'New stitch request',
    adminTitle: 'Boutique admin desk',
    adminIntro: 'PIN-locked desk for visits, stitching orders, and collection stock.',
    adminStaffNote: 'Staff only. Do not share the PIN with customers.',
    adminPin: 'Admin PIN',
    unlockDesk: 'Unlock desk',
    lockDesk: 'Lock desk',
    deskActive: 'Desk unlocked',
    refresh: 'Refresh',
    tabSnapshot: 'Snapshot',
    tabAppointments: 'Visits',
    tabOrders: 'Stitch orders',
    tabVisits: 'Site visits',
    tabCollections: 'Stock & designs',
    collectionsAdminTitle: 'Stock & designs',
    collectionsAdminIntro: 'Upload pieces for the public Collections page. Images are stored securely in the boutique database.',
    collectionsUpload: 'Add piece',
    collectionsTitleField: 'Title',
    collectionsTitleTeField: 'Title (Telugu)',
    collectionsBodyField: 'Description',
    collectionsBodyTeField: 'Description (Telugu)',
    collectionsCategory: 'Category',
    collectionsKind: 'Type',
    collectionsKindStock: 'Stock',
    collectionsKindDesign: 'Design',
    collectionsPublished: 'Published',
    collectionsImage: 'Photo',
    collectionsEmpty: 'No uploaded pieces yet.',
    collectionsDeleteConfirm: 'Remove this piece from collections?',
    collectionsSaved: 'Piece added to collections.',
    snapshotTitle: 'Boutique snapshot',
    noSearchResults: 'No matches for this search.',
    noAppointments: 'No visit requests yet.',
    noOrders: 'No stitch orders yet.',
    searchLabel: 'Search',
    searchAppointments: 'Search visits…',
    searchOrders: 'Search orders…',
    listShowing: '{total} items · page {page}/{pages}',
    prevPage: 'Prev',
    nextPage: 'Next',
    statusNew: 'New',
    statusConfirmed: 'Confirmed',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    statusMeasuring: 'Measuring',
    statusStitching: 'Stitching',
    statusReady: 'Ready',
    statusDelivered: 'Delivered',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    updated: 'Updated',
    deleted: 'Deleted',
    visitsTitle: 'Website traffic',
    visitsHint: 'Privacy-safe daily hits (no stored IPs).',
    visitsToday: 'Today',
    visitsPeriod: 'Period',
    visitsHits: 'Hits',
    visitsUniques: 'Uniques',
    visitsDaily: 'Daily',
    visitsGeo: 'Locations',
    visitsCountry: 'Country',
    visitsCity: 'City',
    visitsEmpty: 'No traffic recorded yet.',
    visitsUnknown: 'Unknown',
    visitsPrivacyNote: 'Location uses CDN country/city headers only when available.',
    testimonialsTitle: 'What customers say',
    testimonialsIntro: 'Neighbours from Kukatpally and nearby who visit the boutique.',
    footerNav: 'Explore',
    footerPrivacy: 'Privacy',
    goAdmin: 'Admin desk',
    footerRoles: 'Reserve a visit · Custom stitch · Call or WhatsApp',
    footerCopyright: '© {year} Ruhi Trends · ruhitrends.com',
    dockBook: 'Reserve',
    langEn: 'EN',
    langTe: 'TE',
    localNow: 'Local time in KPHB 7th Phase',
    wxClear: 'Clear',
    wxCloud: 'Cloudy',
    wxFog: 'Hazy',
    wxRain: 'Rain',
    wxStorm: 'Storm',
    privacyTitle: 'Privacy',
    privacyIntro: 'How Ruhi Trends handles information you share on this website.',
    privacyS1Title: 'What we collect',
    privacyS1Body:
      'When you reserve a visit or request stitching, we collect your name, phone number, and the details you enter in the form so the boutique can contact you.',
    privacyS2Title: 'How we use it',
    privacyS2Body:
      'We use your details only to confirm appointments, discuss measurements, and fulfil stitching or alteration work. We do not sell your information.',
    privacyS3Title: 'Who can see it',
    privacyS3Body:
      'Boutique staff with the admin PIN can see full visit and order details. Public pages never show your phone number.',
    privacyS4Title: 'Site analytics',
    privacyS4Body:
      'We count page visits in aggregate. We do not store IP addresses — only a short-lived daily hash for unique counting, plus optional country/city from the CDN.',
    privacyS5Title: 'Retention',
    privacyS5Body:
      'Visit and order records are kept as needed for boutique operations. You can ask us to update or remove a request by calling the boutique.',
    privacyS6Title: 'Contact',
    privacyS6Body: 'For privacy questions, call the boutique phone listed on this site.',
    privacyContact: 'Contact:',
    privacyUpdated: 'Last updated: August 2026',
    openNow: 'Open now',
    closedNow: 'Closed now',
    hoursShort: '10:00–20:30',
    waVisit: 'WhatsApp visit',
    waStitch: 'WhatsApp stitch',
    waBridal: 'WhatsApp bridal',
    servicesTitle: 'Atelier services',
    servicesIntro: 'Typical turnaround — confirmed in person based on fabric, detailing, and the day’s queue.',
    bridalTitle: 'Bridal & occasion timeline',
    bridalIntro: 'A calm path from first consult to final finish — so wedding week stays light.',
    faqTitle: 'Boutique FAQ',
    faqIntro: 'Quick answers before you visit or request stitching.',
    careTitle: 'Care notes',
    careBody: 'Silk and heavy work pieces prefer soft hanging, gentle steam, and dry-clean when embellished. Ask the desk for fabric-specific guidance.',
    stitchTipTitle: 'Measurement tip',
    stitchTipBody: 'Wear a well-fitting blouse or similar garment when you visit for measurements. Bring reference photos and your fabric / saree if you have them.',
    formAsideVisit: 'Private fittings · Same-day confirmation',
    formAsideStitch: 'Blouse to bridal · Measured in-house',
    lightboxClose: 'Close',
    motifEyebrow: 'Our signature',
    motifTitle: 'Elephant & silk',
    motifBody:
      'The elephant is our house mark — auspicious, graceful, and rooted in tradition. Draped with saree silk, it becomes the quiet symbol of Ruhi Trends: craft, celebration, and care.',
    heroShloka: 'वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥',
    heroShlokaMeaning: 'O Lord with the curved trunk — remove every obstacle from our work, always.',
    ambiencePlay: 'Calm ambience',
    ambiencePause: 'Pause ambience',
  },
  te: {
    topStatsFallback: 'డిజైనర్ బూటిక్ · కూకట్‌పల్లి',
    hours: 'ప్రతిరోజు · ఉదయం 10:00 – రాత్రి 8:30',
    navHome: 'హోమ్',
    navCollections: 'కలెక్షన్స్',
    navAbout: 'మమ్మల్ని సందర్శించండి',
    navBook: 'విజిట్ రిజర్వ్',
    navStitch: 'కస్టమ్ స్టిచ్',
    navAdmin: 'అడ్మిన్',
    bookNow: 'విజిట్ రిజర్వ్ చేయండి',
    callNow: 'కాల్ చేయండి',
    whatsapp: 'వాట్సాప్',
    heroKicker: 'KPHB 7వ ఫేజ్ · కూకట్‌పల్లి',
    heroBrand: 'రూహీ ట్రెండ్స్',
    heroSub: 'కస్టమ్ స్టిచింగ్ & డిజైనర్ ఎత్నిక్ వేర్',
    heroTagline: 'సిల్క్, స్టిచ్, సందర్భ దుస్తులు — కూకట్‌పల్లిలో జాగ్రత్తగా తయారు.',
    ctaQuote: 'ఫిట్టింగ్ రిజర్వ్',
    galleryTitle: 'అటెలియర్',
    galleryIntro: 'ఫ్యాబ్రిక్ నుండి ఫినిష్ వరకు — చీరలు, బ్రైడల్ ఫిట్టింగ్‌లు, కస్టమ్ స్టిచ్.',
    lookbookTitle: 'కలెక్షన్స్',
    lookbookIntro: 'మేము సృష్టించి, స్టైల్ చేసి, ఫినిష్ చేసే లుక్‌ల సంపన్న ఎడిట్.',
    atmosphereLabel: 'అటెలియర్',
    atmosphereBody: 'బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురు · KPHB ఫేజ్ 7 · ప్రతిరోజు ఉదయం 10 – రాత్రి 8:30',
    trustStripTitle: 'నమ్మకమైన స్థానిక బూటిక్',
    trustLiveLabel: 'ఇప్పుడు బూటిక్‌లో',
    trustHours: 'ప్రతిరోజు ఉదయం 10 – రాత్రి 8:30',
    trustHub: 'KPHB 7వ ఫేజ్',
    trustLandmark: 'బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురు',
    trustLandmarkDetail: 'KPHB ఫేజ్ 7',
    trustStitch: 'కస్టమ్ స్టిచ్',
    trustStitchDetail: 'బ్లౌజ్ నుండి బ్రైడల్',
    finalCtaTitle: 'మీ లుక్, జాగ్రత్తగా ఫినిష్',
    finalCtaBody: 'విజిట్ రిజర్వ్, స్టిచింగ్ రిక్వెస్ట్, లేదా కాల్ — ఫ్యాషన్‌కు తగిన స్పష్టతతో ఫిట్టింగ్‌లు నిర్ధారిస్తాం.',
    whyTitle: 'రూహీ ట్రెండ్స్ ప్రత్యేకత',
    whyIntro: 'కస్టమ్ ఎత్నిక్ వేర్ కోసం కూకట్‌పల్లి అటెలియర్ — కొలతలు, ఫినిష్, ఫాలో-అప్.',
    why1Title: 'బెస్పోక్ స్టిచింగ్',
    why1Body: 'బ్లౌజ్ నుండి బ్రైడల్ సెట్ వరకు — ఇంట్లో కొలతలు, సున్నితమైన ఫినిష్.',
    why2Title: 'సందర్భానికి సిద్ధం',
    why2Body: 'పెళ్లి, రిసెప్షన్, పండుగ లుక్‌లు మీ టైమ్‌లైన్‌కు అనుగుణంగా.',
    why3Title: 'సులభంగా దొరుకుతుంది',
    why3Body: 'LIG-140, KPHB 7వ ఫేజ్‌లో బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురుగా.',
    why4Title: 'సులభ షెడ్యూలింగ్',
    why4Body: 'విజిట్ లేదా స్టిచ్ రిక్వెస్ట్ ఆన్‌లైన్ — ఫోన్/వాట్సాప్‌తో నిర్ధారణ.',
    backLabel: '← వెనక్కి',
    backHome: 'హోమ్‌కు వెనక్కి',
    roleTitle: 'మీ లుక్ ప్రారంభించండి',
    roleVisitTitle: 'ప్రైవేట్ బూటిక్ విజిట్',
    roleVisitBody: 'చీరలు, బ్రైడల్ వేర్, ఫిట్టింగ్‌లు — మా డెస్క్‌తో రిజర్వ్డ్ సమయం.',
    roleStitchTitle: 'కస్టమ్ స్టిచ్ రిక్వెస్ట్',
    roleStitchBody: 'గార్మెంట్, ఫ్యాబ్రిక్ నోట్స్, అవసరమైన తేదీ చెప్పండి.',
    roleOfficeTitle: 'మాతో మాట్లాడండి',
    roleOfficeBody: 'ఫిట్టింగ్‌లు, టైమ్‌లైన్‌లకు రూహీ ట్రెండ్స్‌కు కాల్ చేయండి.',
    roleVisitCta: 'విజిట్ రిజర్వ్',
    roleStitchCta: 'రిక్వెస్ట్ ప్రారంభం',
    roleCallCta: 'ఇప్పుడే కాల్',
    collectionsTitle: 'మేము తయారు చేసేవి',
    collectionsIntro: 'రోజువారీ ఎత్నిక్ ఎలిగెన్స్ నుండి బ్రైడల్ స్టేట్‌మెంట్ వరకు — కూకట్‌పల్లి అటెలియర్‌లో ఫినిష్.',
    exploreCollection: 'చూడండి',
    liveBoardTitle: 'బూటిక్ డెస్క్',
    liveBoardIntro: 'ఓపెన్ విజిట్ రిక్వెస్ట్‌లు మరియు యాక్టివ్ స్టిచింగ్ వర్క్.',
    liveAppointmentsTitle: 'విజిట్ రిక్వెస్ట్‌లు',
    liveOrdersTitle: 'స్టిచింగ్ ఆర్డర్లు',
    liveEmptyAppointments: 'ఇంకా విజిట్‌లు లేవు. పైన రిజర్వ్ చేయండి.',
    liveEmptyOrders: 'ఇంకా స్టిచ్ ఆర్డర్లు లేవు. పైన రిక్వెస్ట్ పంపండి.',
    liveColService: 'సేవ',
    liveColGarment: 'గార్మెంట్',
    liveColWhen: 'ఎప్పుడు',
    liveColStatus: 'స్టేటస్',
    marketPulse: 'ఇప్పుడు బూటిక్‌లో',
    snapAppointments: 'ఓపెన్ విజిట్‌లు',
    snapOrders: 'యాక్టివ్ ఆర్డర్లు',
    snapReady: 'తీసుకోవడానికి సిద్ధం',
    aboutTitle: 'రూహీ ట్రెండ్స్ సందర్శించండి',
    aboutIntro: 'KPHB 7వ ఫేజ్, కూకట్‌పల్లిలో బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురుగా.',
    aboutOwnerLabel: 'బూటిక్',
    aboutPhoneLabel: 'ఫోన్',
    aboutAddressLabel: 'చిరునామా',
    aboutHoursLabel: 'సమయాలు',
    aboutHoursValue: 'ప్రతిరోజు · ఉదయం 10:00 – రాత్రి 8:30',
    aboutBody:
      'రూహీ ట్రెండ్స్ (రూహీస్ బూటిక్) కస్టమ్ స్టిచింగ్, బ్రైడల్ కన్సల్టేషన్, చీరలు, లెహెంగాలు, కుర్తీలు, పిల్లల ఎత్నిక్ వేర్, ఆల్టరేషన్స్ అందిస్తుంది. కొలతలకు సమయం కేటాయించడానికి ముందుగా రిజర్వ్ చేయండి.',
    aboutMapTitle: 'లొకేషన్ మ్యాప్',
    ctaDirections: 'దారులు',
    justdial: 'జస్ట్‌డయల్ లిస్టింగ్',
    googleReviews: 'రివ్యూలు',
    bookTitle: 'బూటిక్ విజిట్ రిజర్వ్ చేయండి',
    bookIntro: 'మీకు ఏమి కావాలో చెప్పండి — ఫోన్ లేదా వాట్సాప్‌తో స్లాట్ నిర్ధారిస్తాం.',
    stitchTitle: 'కస్టమ్ స్టిచింగ్ రిక్వెస్ట్',
    stitchIntro: 'గార్మెంట్ వివరాలు పంపండి. కొలతలు, ఫ్యాబ్రిక్ కోసం బూటిక్ ఫాలో అప్ చేస్తుంది.',
    name: 'మీ పేరు',
    phone: 'ఫోన్ / వాట్సాప్',
    serviceType: 'సేవ',
    garmentType: 'గార్మెంట్ రకం',
    fabricNotes: 'ఫ్యాబ్రిక్ / రంగు నోట్స్',
    occasion: 'సందర్భం',
    preferredDate: 'ఇష్టమైన తేదీ',
    preferredTime: 'ఇష్టమైన సమయం',
    notes: 'నోట్స్',
    submitting: 'పంపుతున్నాం…',
    submitBook: 'విజిట్ రిజర్వ్',
    submitStitch: 'స్టిచింగ్ రిక్వెస్ట్',
    formOfficeNote: 'బూటిక్ సమయాల్లో సాధారణంగా అదే రోజు రిప్లై ఇస్తాం.',
    serviceConsultation: 'కన్సల్టేషన్',
    serviceStitching: 'స్టిచింగ్',
    serviceBridal: 'బ్రైడల్',
    serviceAlteration: 'ఆల్టరేషన్',
    serviceParty: 'పార్టీ వేర్',
    garmentBlouse: 'బ్లౌజ్',
    garmentSaree: 'చీర సెట్',
    garmentLehenga: 'లెహెంగా',
    garmentKurti: 'కుర్తీ',
    garmentKids: 'పిల్లల దుస్తులు',
    garmentAlteration: 'ఆల్టరేషన్',
    garmentOther: 'ఇతర',
    timeMorning: 'ఉదయం',
    timeAfternoon: 'మధ్యాహ్నం',
    timeEvening: 'సాయంత్రం',
    confirmBookTitle: 'విజిట్ రిక్వెస్ట్ అందింది',
    confirmStitchTitle: 'స్టిచింగ్ రిక్వెస్ట్ అందింది',
    confirmBackHome: 'హోమ్‌కు వెనక్కి',
    confirmAnotherBook: 'మరో విజిట్ రిజర్వ్',
    confirmAnotherStitch: 'కొత్త స్టిచ్ రిక్వెస్ట్',
    adminTitle: 'బూటిక్ అడ్మిన్ డెస్క్',
    adminIntro: 'విజిట్ రిక్వెస్ట్‌లు మరియు స్టిచింగ్ ఆర్డర్ల కోసం PIN లాక్ డెస్క్.',
    adminStaffNote: 'స్టాఫ్ మాత్రమే. PIN ను కస్టమర్లతో పంచుకోవద్దు.',
    adminPin: 'అడ్మిన్ PIN',
    unlockDesk: 'డెస్క్ అన్‌లాక్',
    lockDesk: 'డెస్క్ లాక్',
    deskActive: 'డెస్క్ అన్‌లాక్ అయింది',
    refresh: 'రిఫ్రెష్',
    tabSnapshot: 'స్నాప్‌షాట్',
    tabAppointments: 'విజిట్‌లు',
    tabOrders: 'స్టిచ్ ఆర్డర్లు',
    tabVisits: 'సైట్ విజిట్‌లు',
    tabCollections: 'స్టాక్ & డిజైన్స్',
    collectionsAdminTitle: 'స్టాక్ & డిజైన్స్',
    collectionsAdminIntro: 'పబ్లిక్ కలెక్షన్స్ పేజీకి పీస్‌లు అప్‌లోడ్ చేయండి. చిత్రాలు బూటిక్ డేటాబేస్‌లో సురక్షితంగా నిల్వ అవుతాయి.',
    collectionsUpload: 'పీస్ జోడించండి',
    collectionsTitleField: 'టైటిల్',
    collectionsTitleTeField: 'టైటిల్ (తెలుగు)',
    collectionsBodyField: 'వివరణ',
    collectionsBodyTeField: 'వివరణ (తెలుగు)',
    collectionsCategory: 'కేటగిరీ',
    collectionsKind: 'రకం',
    collectionsKindStock: 'స్టాక్',
    collectionsKindDesign: 'డిజైన్',
    collectionsPublished: 'ప్రచురితం',
    collectionsImage: 'ఫోటో',
    collectionsEmpty: 'ఇంకా అప్‌లోడ్ చేసిన పీస్‌లు లేవు.',
    collectionsDeleteConfirm: 'ఈ పీస్‌ను కలెక్షన్స్ నుండి తీసివేయాలా?',
    collectionsSaved: 'పీస్ కలెక్షన్స్‌కు జోడించబడింది.',
    snapshotTitle: 'బూటిక్ స్నాప్‌షాట్',
    noSearchResults: 'ఈ సెర్చ్‌కు మ్యాచ్‌లు లేవు.',
    noAppointments: 'ఇంకా విజిట్ రిక్వెస్ట్‌లు లేవు.',
    noOrders: 'ఇంకా స్టిచ్ ఆర్డర్లు లేవు.',
    searchLabel: 'సెర్చ్',
    searchAppointments: 'విజిట్‌లు వెతకండి…',
    searchOrders: 'ఆర్డర్లు వెతకండి…',
    listShowing: '{total} అంశాలు · పేజీ {page}/{pages}',
    prevPage: 'మునుపటి',
    nextPage: 'తర్వాత',
    statusNew: 'కొత్త',
    statusConfirmed: 'నిర్ధారితం',
    statusCompleted: 'పూర్తి',
    statusCancelled: 'రద్దు',
    statusMeasuring: 'కొలతలు',
    statusStitching: 'స్టిచింగ్',
    statusReady: 'సిద్ధం',
    statusDelivered: 'డెలివరీ',
    edit: 'ఎడిట్',
    save: 'సేవ్',
    cancel: 'రద్దు',
    delete: 'తొలగించు',
    updated: 'అప్‌డేట్ అయింది',
    deleted: 'తొలగించబడింది',
    visitsTitle: 'వెబ్‌సైట్ ట్రాఫిక్',
    visitsHint: 'ప్రైవసీ-సేఫ్ డైలీ హిట్స్ (IP స్టోర్ కాదు).',
    visitsToday: 'ఈరోజు',
    visitsPeriod: 'పీరియడ్',
    visitsHits: 'హిట్స్',
    visitsUniques: 'యూనిక్స్',
    visitsDaily: 'రోజువారీ',
    visitsGeo: 'లొకేషన్లు',
    visitsCountry: 'దేశం',
    visitsCity: 'నగరం',
    visitsEmpty: 'ఇంకా ట్రాఫిక్ లేదు.',
    visitsUnknown: 'తెలియదు',
    visitsPrivacyNote: 'లొకేషన్ CDN దేశం/నగరం హెడర్ల నుండి మాత్రమే.',
    testimonialsTitle: 'కస్టమర్ల మాటలు',
    testimonialsIntro: 'కూకట్‌పల్లి, సమీప ప్రాంతాల నుండి బూటిక్ సందర్శించే వారు.',
    footerNav: 'ఎక్స్‌ప్లోర్',
    footerPrivacy: 'ప్రైవసీ',
    goAdmin: 'అడ్మిన్ డెస్క్',
    footerRoles: 'విజిట్ రిజర్వ్ · కస్టమ్ స్టిచ్ · కాల్ లేదా వాట్సాప్',
    footerCopyright: '© {year} రూహీ ట్రెండ్స్ · ruhitrends.com',
    dockBook: 'రిజర్వ్',
    langEn: 'EN',
    langTe: 'TE',
    localNow: 'KPHB 7వ ఫేజ్ స్థానిక సమయం',
    wxClear: 'స్పష్టం',
    wxCloud: 'మేఘాలు',
    wxFog: 'పొగమంచు',
    wxRain: 'వర్షం',
    wxStorm: 'తుఫాను',
    privacyTitle: 'ప్రైవసీ',
    privacyIntro: 'ఈ వెబ్‌సైట్‌లో మీరు పంచుకునే సమాచారాన్ని రూహీ ట్రెండ్స్ ఎలా నిర్వహిస్తుంది.',
    privacyS1Title: 'మేము ఏమి సేకరిస్తాం',
    privacyS1Body:
      'విజిట్ రిజర్వ్ లేదా స్టిచింగ్ రిక్వెస్ట్‌లో మీ పేరు, ఫోన్, ఫారం వివరాలు సేకరిస్తాం — బూటిక్ మిమ్మల్ని సంప్రదించడానికి.',
    privacyS2Title: 'ఎలా ఉపయోగిస్తాం',
    privacyS2Body:
      'అపాయింట్‌మెంట్ నిర్ధారణ, కొలతలు, స్టిచింగ్/ఆల్టరేషన్ కోసం మాత్రమే. మీ సమాచారం అమ్మము.',
    privacyS3Title: 'ఎవరు చూస్తారు',
    privacyS3Body:
      'అడ్మిన్ PIN ఉన్న స్టాఫ్ పూర్తి విజిట్ మరియు ఆర్డర్ వివరాలు చూస్తారు. పబ్లిక్ పేజీల్లో ఫోన్ కనిపించదు.',
    privacyS4Title: 'సైట్ అనలిటిక్స్',
    privacyS4Body:
      'పేజీ విజిట్‌లను అగ్రిగేట్‌గా లెక్కిస్తాం. IP స్టోర్ కాదు — యూనిక్ కౌంట్ కోసం స్వల్పకాలిక హాష్, CDN దేశం/నగరం మాత్రమే.',
    privacyS5Title: 'నిల్వ',
    privacyS5Body:
      'బూటిక్ ఆపరేషన్లకు అవసరమైనంత కాలం రికార్డులు ఉంచుతాం. అప్‌డేట్/తొలగింపు కోసం బూటిక్‌కు కాల్ చేయండి.',
    privacyS6Title: 'సంప్రదించండి',
    privacyS6Body: 'ప్రైవసీ ప్రశ్నలకు ఈ సైట్‌లోని బూటిక్ ఫోన్‌కు కాల్ చేయండి.',
    privacyContact: 'సంప్రదింపు:',
    privacyUpdated: 'చివరి అప్‌డేట్: ఆగస్టు 2026',
    openNow: 'ఇప్పుడు ఓపెన్',
    closedNow: 'ఇప్పుడు క్లోజ్డ్',
    hoursShort: '10:00–20:30',
    waVisit: 'వాట్సాప్ విజిట్',
    waStitch: 'వాట్సాప్ స్టిచ్',
    waBridal: 'వాట్సాప్ బ్రైడల్',
    servicesTitle: 'అటెలియర్ సేవలు',
    servicesIntro: 'సాధారణ టర్న్‌అరౌండ్ — ఫ్యాబ్రిక్, డీటెయిలింగ్, రోజు క్యూ ప్రకారం వ్యక్తిగతంగా నిర్ధారణ.',
    bridalTitle: 'బ్రైడల్ & సందర్భ టైమ్‌లైన్',
    bridalIntro: 'మొదటి కన్సల్ట్ నుండి ఫైనల్ ఫినిష్ వరకు ప్రశాంత మార్గం — పెళ్లి వారం తేలికగా ఉండేలా.',
    faqTitle: 'బూటిక్ FAQ',
    faqIntro: 'విజిట్ లేదా స్టిచ్ రిక్వెస్ట్ ముందు త్వరిత సమాధానాలు.',
    careTitle: 'కేర్ నోట్స్',
    careBody: 'సిల్క్, హెవీ వర్క్ పీస్‌లకు సాఫ్ట్ హ్యాంగ్, జెంటిల్ స్టీమ్, ఎంబెలిష్‌మెంట్ ఉంటే డ్రై-క్లీన్ మంచిది. ఫ్యాబ్రిక్ గైడెన్స్ కోసం డెస్క్‌ను అడగండి.',
    stitchTipTitle: 'కొలతల చిట్కా',
    stitchTipBody: 'కొలతలకు వచ్చేటప్పుడు బాగా సరిపోయే బ్లౌజ్ లేదా సమాన గార్మెంట్ వేసుకోండి. రెఫరెన్స్ ఫోటోలు, ఫ్యాబ్రిక్/చీర తీసుకురండి.',
    formAsideVisit: 'ప్రైవేట్ ఫిట్టింగ్‌లు · అదే రోజు నిర్ధారణ',
    formAsideStitch: 'బ్లౌజ్ నుండి బ్రైడల్ · ఇంట్లో కొలతలు',
    lightboxClose: 'మూసివేయి',
    motifEyebrow: 'మా సంతకం',
    motifTitle: 'ఏనుగు & సిల్క్',
    motifBody:
      'ఏనుగు మా హౌస్ మార్క్ — శుభం, సొగసు, సంప్రదాయం. చీర సిల్క్‌తో కలిసి అది రూహీ ట్రెండ్స్ చిహ్నం: క్రాఫ్ట్, వేడుక, జాగ్రత్త.',
    heroShloka: 'वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥',
    heroShlokaMeaning: 'వక్రతుండ మహాకాయ — అన్ని కార్యాల్లో విఘ్నాలు తొలగించు.',
    ambiencePlay: 'ప్రశాంత సంగీతం',
    ambiencePause: 'సంగీతం ఆపు',
  },
} as const

export type Testimonial = {
  name: string
  place: string
  role: string
  quote: string
}

export const testimonials: Record<Lang, Testimonial[]> = {
  en: [
    {
      name: 'Sravani',
      place: 'KPHB',
      role: 'Bridal customer',
      quote: 'Got my blouse and lehenga fittings done here. Clear timelines and neat finishing.',
    },
    {
      name: 'Meena',
      place: 'Kukatpally',
      role: 'Regular visitor',
      quote: 'Easy to find opposite the basketball ground. Good for everyday kurtis and saree blouses.',
    },
    {
      name: 'Anusha',
      place: 'Miyapur',
      role: 'Party wear',
      quote: 'Reserved a visit online and they confirmed on WhatsApp the same day. Helpful suggestions.',
    },
    {
      name: 'Deepika',
      place: 'JNTU',
      role: 'Alterations',
      quote: 'Quick alteration on a tight blouse. Fit came out perfect before the function.',
    },
  ],
  te: [
    {
      name: 'శ్రావణి',
      place: 'KPHB',
      role: 'బ్రైడల్ కస్టమర్',
      quote: 'బ్లౌజ్, లెహెంగా ఫిట్టింగ్‌లు ఇక్కడే. టైమ్‌లైన్ స్పష్టం, ఫినిషింగ్ బాగుంది.',
    },
    {
      name: 'మీనా',
      place: 'కూకట్‌పల్లి',
      role: 'రెగ్యులర్',
      quote: 'బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురుగా సులభంగా దొరుకుతుంది. కుర్తీలు, బ్లౌజ్‌లకు మంచిది.',
    },
    {
      name: 'అనూష',
      place: 'మియాపూర్',
      role: 'పార్టీ వేర్',
      quote: 'ఆన్‌లైన్ విజిట్ రిజర్వ్ చేశాను — అదే రోజు వాట్సాప్‌లో నిర్ధారణ వచ్చింది.',
    },
    {
      name: 'దీపిక',
      place: 'JNTU',
      role: 'ఆల్టరేషన్',
      quote: 'బిగుసుగా ఉన్న బ్లౌజ్‌కు త్వరిత ఆల్టరేషన్. ఫంక్షన్‌కు ముందు పర్ఫెక్ట్ ఫిట్.',
    },
  ],
}

export type DictKey = keyof typeof dict.en

export function t(lang: Lang, key: DictKey): string {
  return dict[lang][key]
}
