export type Lang = 'en' | 'te'

export const business = {
  name: 'Ruhi Trends',
  shortName: 'Ruhi Trends',
  boutiqueName: "Ruhi's Boutique",
  siteUrl: 'https://ruhitrends.com',
  domain: 'ruhitrends.com',
  owner: 'Ruhi',
  phone: '+919908185597',
  phoneDisplay: '9908185597',
  whatsapp: '919908185597',
  justdialUrl:
    'https://www.justdial.com/Hyderabad/Ruhis-Botique-Opposite-Basket-Ball-Ground-Kukatpally/040PXX40-XX40-240824180839-T6T3_BZDET',
  mapsShareUrl:
    "https://www.google.com/maps/search/?api=1&query=Ruhi's+Boutique+Opposite+Basketball+Ground+Kukatpally+Hyderabad",
  mapsSearchUrl:
    "https://www.google.com/maps/search/?api=1&query=LIG-140+Opposite+Basketball+Ground+KPHB+7th+Phase+Kukatpally",
  mapsEmbedUrl:
    'https://www.google.com/maps?q=17.4728,78.3923&z=16&output=embed',
  lat: 17.4728,
  lng: 78.3923,
}

export const address = {
  plot: 'LIG-140',
  landmark: 'Opposite Basketball Ground',
  locality: 'KPHB 7th Phase, Kukatpally',
  city: 'Hyderabad',
  state: 'Telangana',
  pin: '500072',
  country: 'India',
  line: 'Plot No. LIG-140, Opposite Basketball Ground, KPHB 7th Phase, Kukatpally, Hyderabad, Telangana 500072, India',
}

export const collections = [
  {
    id: 'saree',
    image: '/gallery-saree.jpg',
    en: { title: 'Sarees & blouses', body: 'Silk, georgette, and everyday sarees with custom blouse stitching.' },
    te: { title: 'చీరలు & బ్లౌజులు', body: 'సిల్క్, జార్జెట్, రోజువారీ చీరలు — కస్టమ్ బ్లౌజ్ స్టిచింగ్‌తో.' },
  },
  {
    id: 'lehenga',
    image: '/gallery-bridal.jpg',
    en: { title: 'Lehengas', body: 'Party and festive lehengas with fitting and finishing at the boutique.' },
    te: { title: 'లెహెంగాలు', body: 'పార్టీ, పండుగ లెహెంగాలు — ఫిట్టింగ్, ఫినిషింగ్ బూటిక్‌లోనే.' },
  },
  {
    id: 'bridal',
    image: '/gallery-bridal.jpg',
    en: { title: 'Bridal & occasion', body: 'Bridal wear consultations, measurements, and timeline planning.' },
    te: { title: 'బ్రైడల్ & సందర్భాలు', body: 'బ్రైడల్ వేర్ కన్సల్టేషన్, కొలతలు, టైమ్‌లైన్ ప్లానింగ్.' },
  },
  {
    id: 'kurti',
    image: '/gallery-fitting.jpg',
    en: { title: 'Kurtis & daily wear', body: 'Comfortable kurtis and casual ethnic looks for work and home.' },
    te: { title: 'కుర్తీలు & డైలీ వేర్', body: 'పని, ఇంటికి సౌకర్యవంతమైన కుర్తీలు మరియు ఎత్నిక్ లుక్‌లు.' },
  },
  {
    id: 'kids',
    image: '/gallery-fitting.jpg',
    en: { title: 'Kids wear', body: 'Cute ethnic outfits for children — festivals and family functions.' },
    te: { title: 'పిల్లల దుస్తులు', body: 'పండుగలు, కుటుంబ వేడుకలకు అందమైన పిల్లల ఎత్నిక్ దుస్తులు.' },
  },
  {
    id: 'alter',
    image: '/gallery-stitch.jpg',
    en: { title: 'Alterations', body: 'Quick alterations and restyling for blouses, sarees, and gowns.' },
    te: { title: 'ఆల్టరేషన్స్', body: 'బ్లౌజ్, చీర, గౌన్‌లకు త్వరిత ఆల్టరేషన్ మరియు రీస్టైలింగ్.' },
  },
] as const

export const gallery = [
  { src: '/gallery-saree.jpg', en: 'Saree floor', te: 'చీరల ఫ్లోర్' },
  { src: '/gallery-bridal.jpg', en: 'Bridal looks', te: 'బ్రైడల్ లుక్‌లు' },
  { src: '/gallery-stitch.jpg', en: 'Custom stitch desk', te: 'కస్టమ్ స్టిచ్ డెస్క్' },
  { src: '/gallery-fitting.jpg', en: 'Fitting room', te: 'ఫిట్టింగ్ రూమ్' },
] as const


const dict = {
  en: {
    topStatsFallback: 'Designer boutique · Kukatpally',
    hours: 'Open daily · 10:00 AM – 8:30 PM',
    navHome: 'Home',
    navCollections: 'Collections',
    navAbout: 'Visit us',
    navBook: 'Book visit',
    navStitch: 'Custom stitch',
    navAdmin: 'Admin',
    bookNow: 'Book a visit',
    callNow: 'Call now',
    whatsapp: 'WhatsApp',
    heroKicker: 'KPHB 7th Phase · Kukatpally',
    heroBrand: 'Ruhi Trends',
    heroSub: 'Custom stitching & designer ethnic wear',
    heroTagline: 'A neighbourhood boutique for sarees, bridal looks, and perfect fittings.',
    ctaQuote: 'Book a visit',
    galleryTitle: 'Inside the boutique',
    galleryIntro: 'Saree floor, bridal fittings, and custom stitch work — the craft behind every look.',
    lookbookTitle: 'Lookbook',
    lookbookIntro: 'A quieter browse of what we stitch and style in Kukatpally.',
    atmosphereLabel: 'Visit',
    atmosphereBody: 'Opposite the basketball ground · KPHB Phase 7 · Daily 10 AM – 8:30 PM',
    trustStripTitle: 'Trusted neighbourhood boutique',
    trustLiveLabel: 'At the boutique now',
    trustHours: 'Daily 10 AM – 8:30 PM',
    trustHub: 'Kukatpally',
    trustLandmark: 'Opp. basketball ground',
    trustLandmarkDetail: 'KPHB Phase 7',
    trustStitch: 'Custom stitch',
    trustStitchDetail: 'Blouse to bridal',
    finalCtaTitle: 'Ready for a fitting?',
    finalCtaBody: 'Call, WhatsApp, or book a visit — we confirm measurements the same day when possible.',
    whyTitle: 'Why choose Ruhi Trends?',
    whyIntro: 'Custom work, bridal planning, and everyday ethnic wear — with clear follow-through.',
    why1Title: 'Custom stitching',
    why1Body: 'Blouses, lehengas, kurtis, and alterations measured and finished in-house.',
    why2Title: 'Bridal & party looks',
    why2Body: 'Consultations for weddings, receptions, and festive occasions.',
    why3Title: 'Neighbourhood location',
    why3Body: 'Easy to find — LIG-140, opposite the basketball ground in KPHB 7th Phase.',
    why4Title: 'Book online',
    why4Body: 'Request a visit or stitching order online; we confirm by phone or WhatsApp.',
    backLabel: '← Back',
    backHome: 'Back to home',
    roleTitle: 'How can we help?',
    roleVisitTitle: 'I want to visit',
    roleVisitBody: 'Book a consultation for sarees, bridal wear, or fittings.',
    roleStitchTitle: 'I need stitching',
    roleStitchBody: 'Share garment type, fabric notes, and preferred date.',
    roleOfficeTitle: 'Call the boutique',
    roleOfficeBody: 'Speak with Ruhi Trends for quick help right away.',
    collectionsTitle: 'What we offer',
    collectionsIntro: 'From daily ethnic wear to bridal outfits — stitched and styled in Kukatpally.',
    liveBoardTitle: 'Boutique desk',
    liveBoardIntro: 'Open visit requests and active stitching work at the boutique.',
    liveAppointmentsTitle: 'Visit requests',
    liveOrdersTitle: 'Stitching orders',
    liveEmptyAppointments: 'No open visits yet. Book a visit above.',
    liveEmptyOrders: 'No open stitch orders yet. Request custom stitching above.',
    liveColService: 'Service',
    liveColGarment: 'Garment',
    liveColWhen: 'When',
    liveColStatus: 'Status',
    marketPulse: 'At the boutique now',
    snapAppointments: 'Open visits',
    snapOrders: 'Active orders',
    snapReady: 'Ready to collect',
    aboutTitle: 'Visit Ruhi Trends',
    aboutIntro: 'Find us opposite the basketball ground in KPHB 7th Phase, Kukatpally.',
    aboutOwnerLabel: 'Boutique',
    aboutPhoneLabel: 'Phone',
    aboutAddressLabel: 'Address',
    aboutHoursLabel: 'Hours',
    aboutHoursValue: 'Daily · 10:00 AM – 8:30 PM',
    aboutBody:
      'Ruhi Trends (Ruhi\'s Boutique) offers custom stitching, bridal consultations, sarees, lehengas, kurtis, kids ethnic wear, and alterations. Walk in or book ahead so we can reserve time for measurements.',
    aboutMapTitle: 'Location map',
    ctaDirections: 'Directions',
    justdial: 'Justdial listing',
    googleReviews: 'reviews',
    bookTitle: 'Book a boutique visit',
    bookIntro: 'Tell us what you need — we will confirm your slot by phone or WhatsApp.',
    stitchTitle: 'Request custom stitching',
    stitchIntro: 'Share garment details. The boutique will follow up for measurements and fabric.',
    name: 'Your name',
    phone: 'Phone / WhatsApp',
    serviceType: 'Service',
    garmentType: 'Garment type',
    fabricNotes: 'Fabric / colour notes',
    occasion: 'Occasion',
    preferredDate: 'Preferred date',
    preferredTime: 'Preferred time',
    notes: 'Notes',
    submitting: 'Sending…',
    submitBook: 'Book visit',
    submitStitch: 'Request stitching',
    formOfficeNote: 'We usually reply the same day during boutique hours.',
    serviceConsultation: 'Consultation',
    serviceStitching: 'Stitching',
    serviceBridal: 'Bridal',
    serviceAlteration: 'Alteration',
    serviceParty: 'Party wear',
    garmentBlouse: 'Blouse',
    garmentSaree: 'Saree set',
    garmentLehenga: 'Lehenga',
    garmentKurti: 'Kurti',
    garmentKids: 'Kids wear',
    garmentAlteration: 'Alteration',
    garmentOther: 'Other',
    timeMorning: 'Morning',
    timeAfternoon: 'Afternoon',
    timeEvening: 'Evening',
    confirmBookTitle: 'Visit request received',
    confirmStitchTitle: 'Stitching request received',
    confirmBackHome: 'Back to home',
    confirmAnotherBook: 'Book another visit',
    confirmAnotherStitch: 'New stitch request',
    adminTitle: 'Boutique admin desk',
    adminIntro: 'PIN-locked desk for visit requests and stitching orders.',
    adminStaffNote: 'Staff only. Do not share the PIN with customers.',
    adminPin: 'Admin PIN',
    unlockDesk: 'Unlock desk',
    lockDesk: 'Lock desk',
    deskActive: 'Desk unlocked',
    refresh: 'Refresh',
    tabSnapshot: 'Snapshot',
    tabAppointments: 'Visits',
    tabOrders: 'Stitch orders',
    tabVisits: 'Site visits',
    snapshotTitle: 'Boutique snapshot',
    noSearchResults: 'No matches for this search.',
    noAppointments: 'No visit requests yet.',
    noOrders: 'No stitch orders yet.',
    searchLabel: 'Search',
    searchAppointments: 'Search visits…',
    searchOrders: 'Search orders…',
    listShowing: '{total} items · page {page}/{pages}',
    prevPage: 'Prev',
    nextPage: 'Next',
    statusNew: 'New',
    statusConfirmed: 'Confirmed',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    statusMeasuring: 'Measuring',
    statusStitching: 'Stitching',
    statusReady: 'Ready',
    statusDelivered: 'Delivered',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    updated: 'Updated',
    deleted: 'Deleted',
    visitsTitle: 'Website traffic',
    visitsHint: 'Privacy-safe daily hits (no stored IPs).',
    visitsToday: 'Today',
    visitsPeriod: 'Period',
    visitsHits: 'Hits',
    visitsUniques: 'Uniques',
    visitsDaily: 'Daily',
    visitsGeo: 'Locations',
    visitsCountry: 'Country',
    visitsCity: 'City',
    visitsEmpty: 'No traffic recorded yet.',
    visitsUnknown: 'Unknown',
    visitsPrivacyNote: 'Location uses CDN country/city headers only when available.',
    testimonialsTitle: 'What customers say',
    testimonialsIntro: 'Neighbours from Kukatpally and nearby who visit the boutique.',
    footerNav: 'Explore',
    footerPrivacy: 'Privacy',
    goAdmin: 'Admin desk',
    footerRoles: 'Book a visit · Custom stitch · Call or WhatsApp',
    footerCopyright: '© {year} Ruhi Trends · ruhitrends.com',
    dockBook: 'Book',
    langEn: 'EN',
    langTe: 'TE',
    localNow: 'Local time in Kukatpally',
    wxClear: 'Clear',
    wxCloud: 'Cloudy',
    wxFog: 'Hazy',
    wxRain: 'Rain',
    wxStorm: 'Storm',
    privacyTitle: 'Privacy',
    privacyIntro: 'How Ruhi Trends handles information you share on this website.',
    privacyS1Title: 'What we collect',
    privacyS1Body:
      'When you book a visit or request stitching, we collect your name, phone number, and the details you enter in the form so the boutique can contact you.',
    privacyS2Title: 'How we use it',
    privacyS2Body:
      'We use your details only to confirm appointments, discuss measurements, and fulfil stitching or alteration work. We do not sell your information.',
    privacyS3Title: 'Who can see it',
    privacyS3Body:
      'Boutique staff with the admin PIN can see full booking details. Public pages never show your phone number.',
    privacyS4Title: 'Site analytics',
    privacyS4Body:
      'We count page visits in aggregate. We do not store IP addresses — only a short-lived daily hash for unique counting, plus optional country/city from the CDN.',
    privacyS5Title: 'Retention',
    privacyS5Body:
      'Booking and order records are kept as needed for boutique operations. You can ask us to update or remove a request by calling the boutique.',
    privacyS6Title: 'Contact',
    privacyS6Body: 'For privacy questions, call the boutique phone listed on this site.',
    privacyContact: 'Contact:',
    privacyUpdated: 'Last updated: August 2026',
  },
  te: {
    topStatsFallback: 'డిజైనర్ బూటిక్ · కూకట్‌పల్లి',
    hours: 'ప్రతిరోజు · ఉదయం 10:00 – రాత్రి 8:30',
    navHome: 'హోమ్',
    navCollections: 'కలెక్షన్స్',
    navAbout: 'మమ్మల్ని సందర్శించండి',
    navBook: 'విజిట్ బుక్',
    navStitch: 'కస్టమ్ స్టిచ్',
    navAdmin: 'అడ్మిన్',
    bookNow: 'విజిట్ బుక్ చేయండి',
    callNow: 'కాల్ చేయండి',
    whatsapp: 'వాట్సాప్',
    heroKicker: 'KPHB 7వ ఫేజ్ · కూకట్‌పల్లి',
    heroBrand: 'రూహీ ట్రెండ్స్',
    heroSub: 'కస్టమ్ స్టిచింగ్ & డిజైనర్ ఎత్నిక్ వేర్',
    heroTagline: 'చీరలు, బ్రైడల్ లుక్‌లు, పర్ఫెక్ట్ ఫిట్టింగ్‌ల కోసం స్థానిక బూటిక్.',
    ctaQuote: 'విజిట్ బుక్ చేయండి',
    galleryTitle: 'బూటిక్ లోపల',
    galleryIntro: 'చీరల ఫ్లోర్, బ్రైడల్ ఫిట్టింగ్‌లు, కస్టమ్ స్టిచ్ వర్క్ — ప్రతి లుక్ వెనుక చేతిపని.',
    lookbookTitle: 'లుక్‌బుక్',
    lookbookIntro: 'కూకట్‌పల్లిలో మేము స్టైల్ చేసే దుస్తుల నిశ్శబ్ద గ్యాలరీ.',
    atmosphereLabel: 'సందర్శన',
    atmosphereBody: 'బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురు · KPHB ఫేజ్ 7 · ప్రతిరోజు ఉదయం 10 – రాత్రి 8:30',
    trustStripTitle: 'నమ్మకమైన స్థానిక బూటిక్',
    trustLiveLabel: 'ఇప్పుడు బూటిక్‌లో',
    trustHours: 'ప్రతిరోజు ఉదయం 10 – రాత్రి 8:30',
    trustHub: 'కూకట్‌పల్లి',
    trustLandmark: 'బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురు',
    trustLandmarkDetail: 'KPHB ఫేజ్ 7',
    trustStitch: 'కస్టమ్ స్టిచ్',
    trustStitchDetail: 'బ్లౌజ్ నుండి బ్రైడల్',
    finalCtaTitle: 'ఫిట్టింగ్‌కు సిద్ధమా?',
    finalCtaBody: 'కాల్, వాట్సాప్, లేదా విజిట్ బుక్ — సాధ్యమైతే అదే రోజు కొలతలు నిర్ధారిస్తాం.',
    whyTitle: 'రూహీ ట్రెండ్స్ ఎందుకు?',
    whyIntro: 'కస్టమ్ వర్క్, బ్రైడల్ ప్లానింగ్, రోజువారీ ఎత్నిక్ వేర్ — స్పష్టమైన ఫాలో-అప్‌తో.',
    why1Title: 'కస్టమ్ స్టిచింగ్',
    why1Body: 'బ్లౌజ్, లెహెంగా, కుర్తీ, ఆల్టరేషన్స్ — కొలతలు, ఫినిషింగ్ ఇంట్లోనే.',
    why2Title: 'బ్రైడల్ & పార్టీ లుక్‌లు',
    why2Body: 'పెళ్లి, రిసెప్షన్, పండుగ సందర్భాలకు కన్సల్టేషన్.',
    why3Title: 'సులభమైన లొకేషన్',
    why3Body: 'LIG-140, KPHB 7వ ఫేజ్‌లో బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురుగా.',
    why4Title: 'ఆన్‌లైన్ బుకింగ్',
    why4Body: 'విజిట్ లేదా స్టిచింగ్ రిక్వెస్ట్ ఆన్‌లైన్ పంపండి; ఫోన్/వాట్సాప్‌తో నిర్ధారిస్తాం.',
    backLabel: '← వెనక్కి',
    backHome: 'హోమ్‌కు వెనక్కి',
    roleTitle: 'మీకు ఏమి కావాలి?',
    roleVisitTitle: 'విజిట్ చేయాలి',
    roleVisitBody: 'చీరలు, బ్రైడల్ వేర్, ఫిట్టింగ్‌లకు కన్సల్టేషన్ బుక్ చేయండి.',
    roleStitchTitle: 'స్టిచింగ్ కావాలి',
    roleStitchBody: 'గార్మెంట్ రకం, ఫ్యాబ్రిక్ నోట్స్, తేదీ పంపండి.',
    roleOfficeTitle: 'బూటిక్‌కు కాల్',
    roleOfficeBody: 'త్వరిత సహాయం కోసం రూహీ ట్రెండ్స్‌తో మాట్లాడండి.',
    collectionsTitle: 'మా సేవలు',
    collectionsIntro: 'రోజువారీ ఎత్నిక్ వేర్ నుండి బ్రైడల్ వరకు — కూకట్‌పల్లిలో స్టైల్.',
    liveBoardTitle: 'బూటిక్ డెస్క్',
    liveBoardIntro: 'ఓపెన్ విజిట్ రిక్వెస్ట్‌లు మరియు యాక్టివ్ స్టిచింగ్ వర్క్.',
    liveAppointmentsTitle: 'విజిట్ రిక్వెస్ట్‌లు',
    liveOrdersTitle: 'స్టిచింగ్ ఆర్డర్లు',
    liveEmptyAppointments: 'ఇంకా విజిట్‌లు లేవు. పైన బుక్ చేయండి.',
    liveEmptyOrders: 'ఇంకా స్టిచ్ ఆర్డర్లు లేవు. పైన రిక్వెస్ట్ పంపండి.',
    liveColService: 'సేవ',
    liveColGarment: 'గార్మెంట్',
    liveColWhen: 'ఎప్పుడు',
    liveColStatus: 'స్టేటస్',
    marketPulse: 'ఇప్పుడు బూటిక్‌లో',
    snapAppointments: 'ఓపెన్ విజిట్‌లు',
    snapOrders: 'యాక్టివ్ ఆర్డర్లు',
    snapReady: 'తీసుకోవడానికి సిద్ధం',
    aboutTitle: 'రూహీ ట్రెండ్స్ సందర్శించండి',
    aboutIntro: 'KPHB 7వ ఫేజ్, కూకట్‌పల్లిలో బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురుగా.',
    aboutOwnerLabel: 'బూటిక్',
    aboutPhoneLabel: 'ఫోన్',
    aboutAddressLabel: 'చిరునామా',
    aboutHoursLabel: 'సమయాలు',
    aboutHoursValue: 'ప్రతిరోజు · ఉదయం 10:00 – రాత్రి 8:30',
    aboutBody:
      'రూహీ ట్రెండ్స్ (రూహీస్ బూటిక్) కస్టమ్ స్టిచింగ్, బ్రైడల్ కన్సల్టేషన్, చీరలు, లెహెంగాలు, కుర్తీలు, పిల్లల ఎత్నిక్ వేర్, ఆల్టరేషన్స్ అందిస్తుంది. కొలతలకు సమయం రిజర్వ్ చేయడానికి ముందుగా బుక్ చేయండి.',
    aboutMapTitle: 'లొకేషన్ మ్యాప్',
    ctaDirections: 'దారులు',
    justdial: 'జస్ట్‌డయల్ లిస్టింగ్',
    googleReviews: 'రివ్యూలు',
    bookTitle: 'బూటిక్ విజిట్ బుక్ చేయండి',
    bookIntro: 'మీకు ఏమి కావాలో చెప్పండి — ఫోన్ లేదా వాట్సాప్‌తో స్లాట్ నిర్ధారిస్తాం.',
    stitchTitle: 'కస్టమ్ స్టిచింగ్ రిక్వెస్ట్',
    stitchIntro: 'గార్మెంట్ వివరాలు పంపండి. కొలతలు, ఫ్యాబ్రిక్ కోసం బూటిక్ ఫాలో అప్ చేస్తుంది.',
    name: 'మీ పేరు',
    phone: 'ఫోన్ / వాట్సాప్',
    serviceType: 'సేవ',
    garmentType: 'గార్మెంట్ రకం',
    fabricNotes: 'ఫ్యాబ్రిక్ / రంగు నోట్స్',
    occasion: 'సందర్భం',
    preferredDate: 'ఇష్టమైన తేదీ',
    preferredTime: 'ఇష్టమైన సమయం',
    notes: 'నోట్స్',
    submitting: 'పంపుతున్నాం…',
    submitBook: 'విజిట్ బుక్',
    submitStitch: 'స్టిచింగ్ రిక్వెస్ట్',
    formOfficeNote: 'బూటిక్ సమయాల్లో సాధారణంగా అదే రోజు రిప్లై ఇస్తాం.',
    serviceConsultation: 'కన్సల్టేషన్',
    serviceStitching: 'స్టిచింగ్',
    serviceBridal: 'బ్రైడల్',
    serviceAlteration: 'ఆల్టరేషన్',
    serviceParty: 'పార్టీ వేర్',
    garmentBlouse: 'బ్లౌజ్',
    garmentSaree: 'చీర సెట్',
    garmentLehenga: 'లెహెంగా',
    garmentKurti: 'కుర్తీ',
    garmentKids: 'పిల్లల దుస్తులు',
    garmentAlteration: 'ఆల్టరేషన్',
    garmentOther: 'ఇతర',
    timeMorning: 'ఉదయం',
    timeAfternoon: 'మధ్యాహ్నం',
    timeEvening: 'సాయంత్రం',
    confirmBookTitle: 'విజిట్ రిక్వెస్ట్ అందింది',
    confirmStitchTitle: 'స్టిచింగ్ రిక్వెస్ట్ అందింది',
    confirmBackHome: 'హోమ్‌కు వెనక్కి',
    confirmAnotherBook: 'మరో విజిట్ బుక్',
    confirmAnotherStitch: 'కొత్త స్టిచ్ రిక్వెస్ట్',
    adminTitle: 'బూటిక్ అడ్మిన్ డెస్క్',
    adminIntro: 'విజిట్ రిక్వెస్ట్‌లు మరియు స్టిచింగ్ ఆర్డర్ల కోసం PIN లాక్ డెస్క్.',
    adminStaffNote: 'స్టాఫ్ మాత్రమే. PIN ను కస్టమర్లతో పంచుకోవద్దు.',
    adminPin: 'అడ్మిన్ PIN',
    unlockDesk: 'డెస్క్ అన్‌లాక్',
    lockDesk: 'డెస్క్ లాక్',
    deskActive: 'డెస్క్ అన్‌లాక్ అయింది',
    refresh: 'రిఫ్రెష్',
    tabSnapshot: 'స్నాప్‌షాట్',
    tabAppointments: 'విజిట్‌లు',
    tabOrders: 'స్టిచ్ ఆర్డర్లు',
    tabVisits: 'సైట్ విజిట్‌లు',
    snapshotTitle: 'బూటిక్ స్నాప్‌షాట్',
    noSearchResults: 'ఈ సెర్చ్‌కు మ్యాచ్‌లు లేవు.',
    noAppointments: 'ఇంకా విజిట్ రిక్వెస్ట్‌లు లేవు.',
    noOrders: 'ఇంకా స్టిచ్ ఆర్డర్లు లేవు.',
    searchLabel: 'సెర్చ్',
    searchAppointments: 'విజిట్‌లు వెతకండి…',
    searchOrders: 'ఆర్డర్లు వెతకండి…',
    listShowing: '{total} అంశాలు · పేజీ {page}/{pages}',
    prevPage: 'మునుపటి',
    nextPage: 'తర్వాత',
    statusNew: 'కొత్త',
    statusConfirmed: 'నిర్ధారితం',
    statusCompleted: 'పూర్తి',
    statusCancelled: 'రద్దు',
    statusMeasuring: 'కొలతలు',
    statusStitching: 'స్టిచింగ్',
    statusReady: 'సిద్ధం',
    statusDelivered: 'డెలివరీ',
    edit: 'ఎడిట్',
    save: 'సేవ్',
    cancel: 'రద్దు',
    delete: 'తొలగించు',
    updated: 'అప్‌డేట్ అయింది',
    deleted: 'తొలగించబడింది',
    visitsTitle: 'వెబ్‌సైట్ ట్రాఫిక్',
    visitsHint: 'ప్రైవసీ-సేఫ్ డైలీ హిట్స్ (IP స్టోర్ కాదు).',
    visitsToday: 'ఈరోజు',
    visitsPeriod: 'పీరియడ్',
    visitsHits: 'హిట్స్',
    visitsUniques: 'యూనిక్స్',
    visitsDaily: 'రోజువారీ',
    visitsGeo: 'లొకేషన్లు',
    visitsCountry: 'దేశం',
    visitsCity: 'నగరం',
    visitsEmpty: 'ఇంకా ట్రాఫిక్ లేదు.',
    visitsUnknown: 'తెలియదు',
    visitsPrivacyNote: 'లొకేషన్ CDN దేశం/నగరం హెడర్ల నుండి మాత్రమే.',
    testimonialsTitle: 'కస్టమర్ల మాటలు',
    testimonialsIntro: 'కూకట్‌పల్లి, సమీప ప్రాంతాల నుండి బూటిక్ సందర్శించే వారు.',
    footerNav: 'ఎక్స్‌ప్లోర్',
    footerPrivacy: 'ప్రైవసీ',
    goAdmin: 'అడ్మిన్ డెస్క్',
    footerRoles: 'విజిట్ బుక్ · కస్టమ్ స్టిచ్ · కాల్ లేదా వాట్సాప్',
    footerCopyright: '© {year} రూహీ ట్రెండ్స్ · ruhitrends.com',
    dockBook: 'బుక్',
    langEn: 'EN',
    langTe: 'TE',
    localNow: 'కూకట్‌పల్లి స్థానిక సమయం',
    wxClear: 'స్పష్టం',
    wxCloud: 'మేఘాలు',
    wxFog: 'పొగమంచు',
    wxRain: 'వర్షం',
    wxStorm: 'తుఫాను',
    privacyTitle: 'ప్రైవసీ',
    privacyIntro: 'ఈ వెబ్‌సైట్‌లో మీరు పంచుకునే సమాచారాన్ని రూహీ ట్రెండ్స్ ఎలా నిర్వహిస్తుంది.',
    privacyS1Title: 'మేము ఏమి సేకరిస్తాం',
    privacyS1Body:
      'విజిట్ బుక్ లేదా స్టిచింగ్ రిక్వెస్ట్‌లో మీ పేరు, ఫోన్, ఫారం వివరాలు సేకరిస్తాం — బూటిక్ మిమ్మల్ని సంప్రదించడానికి.',
    privacyS2Title: 'ఎలా ఉపయోగిస్తాం',
    privacyS2Body:
      'అపాయింట్‌మెంట్ నిర్ధారణ, కొలతలు, స్టిచింగ్/ఆల్టరేషన్ కోసం మాత్రమే. మీ సమాచారం అమ్మము.',
    privacyS3Title: 'ఎవరు చూస్తారు',
    privacyS3Body:
      'అడ్మిన్ PIN ఉన్న స్టాఫ్ పూర్తి బుకింగ్ వివరాలు చూస్తారు. పబ్లిక్ పేజీల్లో ఫోన్ కనిపించదు.',
    privacyS4Title: 'సైట్ అనలిటిక్స్',
    privacyS4Body:
      'పేజీ విజిట్‌లను అగ్రిగేట్‌గా లెక్కిస్తాం. IP స్టోర్ కాదు — యూనిక్ కౌంట్ కోసం స్వల్పకాలిక హాష్, CDN దేశం/నగరం మాత్రమే.',
    privacyS5Title: 'నిల్వ',
    privacyS5Body:
      'బూటిక్ ఆపరేషన్లకు అవసరమైనంత కాలం రికార్డులు ఉంచుతాం. అప్‌డేట్/తొలగింపు కోసం బూటిక్‌కు కాల్ చేయండి.',
    privacyS6Title: 'సంప్రదించండి',
    privacyS6Body: 'ప్రైవసీ ప్రశ్నలకు ఈ సైట్‌లోని బూటిక్ ఫోన్‌కు కాల్ చేయండి.',
    privacyContact: 'సంప్రదింపు:',
    privacyUpdated: 'చివరి అప్‌డేట్: ఆగస్టు 2026',
  },
} as const

export type Testimonial = {
  name: string
  place: string
  role: string
  quote: string
}

export const testimonials: Record<Lang, Testimonial[]> = {
  en: [
    {
      name: 'Sravani',
      place: 'KPHB',
      role: 'Bridal customer',
      quote: 'Got my blouse and lehenga fittings done here. Clear timelines and neat finishing.',
    },
    {
      name: 'Meena',
      place: 'Kukatpally',
      role: 'Regular visitor',
      quote: 'Easy to find opposite the basketball ground. Good for everyday kurtis and saree blouses.',
    },
    {
      name: 'Anusha',
      place: 'Miyapur',
      role: 'Party wear',
      quote: 'Booked a visit online and they confirmed on WhatsApp the same day. Helpful suggestions.',
    },
    {
      name: 'Deepika',
      place: 'JNTU',
      role: 'Alterations',
      quote: 'Quick alteration on a tight blouse. Fit came out perfect before the function.',
    },
  ],
  te: [
    {
      name: 'శ్రావణి',
      place: 'KPHB',
      role: 'బ్రైడల్ కస్టమర్',
      quote: 'బ్లౌజ్, లెహెంగా ఫిట్టింగ్‌లు ఇక్కడే. టైమ్‌లైన్ స్పష్టం, ఫినిషింగ్ బాగుంది.',
    },
    {
      name: 'మీనా',
      place: 'కూకట్‌పల్లి',
      role: 'రెగ్యులర్',
      quote: 'బాస్కెట్‌బాల్ గ్రౌండ్ ఎదురుగా సులభంగా దొరుకుతుంది. కుర్తీలు, బ్లౌజ్‌లకు మంచిది.',
    },
    {
      name: 'అనూష',
      place: 'మియాపూర్',
      role: 'పార్టీ వేర్',
      quote: 'ఆన్‌లైన్ విజిట్ బుక్ చేశాను — అదే రోజు వాట్సాప్‌లో నిర్ధారణ వచ్చింది.',
    },
    {
      name: 'దీపిక',
      place: 'JNTU',
      role: 'ఆల్టరేషన్',
      quote: 'బిగుసుగా ఉన్న బ్లౌజ్‌కు త్వరిత ఆల్టరేషన్. ఫంక్షన్‌కు ముందు పర్ఫెక్ట్ ఫిట్.',
    },
  ],
}

export type DictKey = keyof typeof dict.en

export function t(lang: Lang, key: DictKey): string {
  return dict[lang][key]
}
